const QUERY_API = 'QUERY_API';
/** Пользователи */
const USERS_CURRENT_REQUEST_SUCCESSED = 'USERS_CURRENT_REQUEST_SUCCESSED';
const USERS_REQUEST_SUCCESSED = 'USERS_REQUEST_SUCCESSED';

/** Должности */
const POSITIONS_REQUEST_SUCCESSED = 'POSITIONS_REQUEST_SUCCESSED';
const POSITIONS_UPDATE = 'POSITIONS_UPDATE';
/** Потребности */
const NEEDS_FETCH = 'NEEDS_FETCH';
const NEEDS_REQUEST_SUCCESSED = 'NEEDS_REQUEST_SUCCESSED';
const NEEDS_LOADED_REQUEST_SUCCESSED = 'NEEDS_LOADED_REQUEST_SUCCESSED';
const NEEDS_UPDATE = 'NEEDS_UPDATE';
/** Доступы */
const RULES_REQUEST_SUCCESSED = 'RULES_REQUEST_SUCCESSED';
const RULES_UPDATE = 'RULES_UPDATE';

/** Константы для авторизации */
const AUTH_REQUEST_SUCCESSED = 'AUTH_REQUEST_SUCCESSED';

/** Договора */
const CONTRACT_REQUEST_SUCCESSED = 'CONTRACT_REQUEST_SUCCESSED';

/** Фильтр */
const FILTER_IRRELEVANT_UPDATE = 'FILTER_IRRELEVANT_UPDATE';
const FILTER_SHOW_ME_UPDATE = 'FILTER_SHOW_ME_UPDATE';

export {
  QUERY_API,
  USERS_CURRENT_REQUEST_SUCCESSED,
  USERS_REQUEST_SUCCESSED,
  POSITIONS_REQUEST_SUCCESSED,
  POSITIONS_UPDATE,
  AUTH_REQUEST_SUCCESSED,
  CONTRACT_REQUEST_SUCCESSED,
  RULES_REQUEST_SUCCESSED,
  RULES_UPDATE,
  NEEDS_LOADED_REQUEST_SUCCESSED,
  NEEDS_REQUEST_SUCCESSED,
  NEEDS_UPDATE,
  NEEDS_FETCH,
  FILTER_IRRELEVANT_UPDATE,
  FILTER_SHOW_ME_UPDATE,
};
