const QUERY_API = 'QUERY_API';
/** Пользователи */
const USERS_CURRENT_REQUEST_SUCCESSED = 'USERS_CURRENT_REQUEST_SUCCESSED';
const USERS_REQUEST_SUCCESSED = 'USERS_REQUEST_SUCCESSED';

/** Должности */
const POSITIONS_REQUEST_SUCCESSED = 'POSITIONS_REQUEST_SUCCESSED';
const POSITIONS_UPDATE = 'POSITIONS_UPDATE';

/** Константы для авторизации */
const AUTH_REQUEST_SUCCESSED = 'AUTH_REQUEST_SUCCESSED';

/** Договора */
const CONTRACT_REQUEST_SUCCESSED = 'CONTRACT_REQUEST_SUCCESSED';

export {
  QUERY_API,
  USERS_CURRENT_REQUEST_SUCCESSED,
  USERS_REQUEST_SUCCESSED,
  POSITIONS_REQUEST_SUCCESSED,
  POSITIONS_UPDATE,
  AUTH_REQUEST_SUCCESSED,
  CONTRACT_REQUEST_SUCCESSED,
};
