const QUERY_API = 'QUERY_API';
/** Пользователи */
const USERS_REQUEST_SUCCESSED = 'USERS_REQUEST_SUCCESSED';
const USERS_UPDATE = 'USERS_UPDATE';
const USERS_CURRENT_REQUEST_SUCCESSED = 'USERS_CURRENT_REQUEST_SUCCESSED';
const USERS_CURRENT_UPDATE = 'USERS_CURRENT_UPDATE';

/** Должности */
const POSITIONS_REQUEST_SUCCESSED = 'POSITIONS_REQUEST_SUCCESSED';
const POSITIONS_UPDATE = 'POSITIONS_UPDATE';

export default {
  QUERY_API,
  USERS_REQUEST_SUCCESSED,
  USERS_UPDATE,
  USERS_CURRENT_REQUEST_SUCCESSED,
  USERS_CURRENT_UPDATE,
  POSITIONS_REQUEST_SUCCESSED,
  POSITIONS_UPDATE,
};
